const countries = {
    'Andorra' : { id : 'AD', countryName : 'Andorra', countryCode : 'AD'},
    'United Arab Emirates' : { id : 'AE', countryName : 'United Arab Emirates', countryCode : 'AE'},
    'Afghanistan' : { id : 'AF', countryName : 'Afghanistan', countryCode : 'AF'},
    'Antigua and Barbuda' : { id : 'AG', countryName : 'Antigua and Barbuda', countryCode : 'AG'},
    'Anguilla' : { id : 'AI', countryName : 'Anguilla', countryCode : 'AI'},
    'Albania' : { id : 'AL', countryName : 'Albania', countryCode : 'AL'},
    'Armenia' : { id : 'AM', countryName : 'Armenia', countryCode : 'AM'},
    'Netherlands Antilles' : { id : 'AN', countryName : 'Netherlands Antilles', countryCode : 'AN'},
    'Angola' : { id : 'AO', countryName : 'Angola', countryCode : 'AO'},
    'Antarctica' : { id : 'AQ', countryName : 'Antarctica', countryCode : 'AQ'},
    'Argentina' : { id : 'AR', countryName : 'Argentina', countryCode : 'AR'},
    'American Samoa' : { id : 'AS', countryName : 'American Samoa', countryCode : 'AS'},
    'Austria' : { id : 'AT', countryName : 'Austria', countryCode : 'AT'},
    'Australia' : { id : 'AU', countryName : 'Australia', countryCode : 'AU'},
    'Aruba' : { id : 'AW', countryName : 'Aruba', countryCode : 'AW'},
    'Azerbaijan' : { id : 'AZ', countryName : 'Azerbaijan', countryCode : 'AZ'},
    'Bosnia and Herzegovina' : { id : 'BA', countryName : 'Bosnia and Herzegovina', countryCode : 'BA'},
    'Barbados' : { id : 'BB', countryName : 'Barbados', countryCode : 'BB'},
    'Bangladesh' : { id : 'BD', countryName : 'Bangladesh', countryCode : 'BD'},
    'Belgium' : { id : 'BE', countryName : 'Belgium', countryCode : 'BE'},
    'Burkina Faso' : { id : 'BF', countryName : 'Burkina Faso', countryCode : 'BF'},
    'Bulgaria' : { id : 'BG', countryName : 'Bulgaria', countryCode : 'BG'},
    'Bahrain' : { id : 'BH', countryName : 'Bahrain', countryCode : 'BH'},
    'Burundi' : { id : 'BI', countryName : 'Burundi', countryCode : 'BI'},
    'Benin' : { id : 'BJ', countryName : 'Benin', countryCode : 'BJ'},
    'Bermuda' : { id : 'BM', countryName : 'Bermuda', countryCode : 'BM'},
    'Brunei' : { id : 'BN', countryName : 'Brunei', countryCode : 'BN'},
    'Bolivia' : { id : 'BO', countryName : 'Bolivia', countryCode : 'BO'},
    'Brazil' : { id : 'BR', countryName : 'Brazil', countryCode : 'BR'},
    'Bahamas' : { id : 'BS', countryName : 'Bahamas', countryCode : 'BS'},
    'Bhutan' : { id : 'BT', countryName : 'Bhutan', countryCode : 'BT'},
    'Bouvet Island' : { id : 'BV', countryName : 'Bouvet Island', countryCode : 'BV'},
    'Botswana' : { id : 'BW', countryName : 'Botswana', countryCode : 'BW'},
    'Belarus' : { id : 'BY', countryName : 'Belarus', countryCode : 'BY'},
    'Belize' : { id : 'BZ', countryName : 'Belize', countryCode : 'BZ'},
    'Canada' : { id : 'CA', countryName : 'Canada', countryCode : 'CA'},
    'Cocos [Keeling] Islands' : { id : 'CC', countryName : 'Cocos [Keeling] Islands', countryCode : 'CC'},
    'Congo [DRC]' : { id : 'CD', countryName : 'Congo [DRC]', countryCode : 'CD'},
    'Central African Republic' : { id : 'CF', countryName : 'Central African Republic', countryCode : 'CF'},
    'Congo [Republic]' : { id : 'CG', countryName : 'Congo [Republic]', countryCode : 'CG'},
    'Switzerland' : { id : 'CH', countryName : 'Switzerland', countryCode : 'CH'},
    "Côte d'Ivoire" : { id : 'CI', countryName : "Côte d'Ivoire", countryCode : 'CI'},
    'Cook Islands' : { id : 'CK', countryName : 'Cook Islands', countryCode : 'CK'},
    'Chile' : { id : 'CL', countryName : 'Chile', countryCode : 'CL'},
    'Cameroon' : { id : 'CM', countryName : 'Cameroon', countryCode : 'CM'},
    'China' : { id : 'CN', countryName : 'China', countryCode : 'CN'},
    'Colombia' : { id : 'CO', countryName : 'Colombia', countryCode : 'CO'},
    'Costa Rica' : { id : 'CR', countryName : 'Costa Rica', countryCode : 'CR'},
    'Cuba' : { id : 'CU', countryName : 'Cuba', countryCode : 'CU'},
    'Cape Verde' : { id : 'CV', countryName : 'Cape Verde', countryCode : 'CV'},
    'Christmas Island' : { id : 'CX', countryName : 'Christmas Island', countryCode : 'CX'},
    'Cyprus' : { id : 'CY', countryName : 'Cyprus', countryCode : 'CY'},
    'Czech Republic' : { id : 'CZ', countryName : 'Czech Republic', countryCode : 'CZ'},
    'Germany' : { id : 'DE', countryName : 'Germany', countryCode : 'DE'},
    'Djibouti' : { id : 'DJ', countryName : 'Djibouti', countryCode : 'DJ'},
    'Denmark' : { id : 'DK', countryName : 'Denmark', countryCode : 'DK'},
    'Dominica' : { id : 'DM', countryName : 'Dominica', countryCode : 'DM'},
    'Dominican Republic' : { id : 'DO', countryName : 'Dominican Republic', countryCode : 'DO'},
    'Algeria' : { id : 'DZ', countryName : 'Algeria', countryCode : 'DZ'},
    'Ecuador' : { id : 'EC', countryName : 'Ecuador', countryCode : 'EC'},
    'Estonia' : { id : 'EE', countryName : 'Estonia', countryCode : 'EE'},
    'Egypt' : { id : 'EG', countryName : 'Egypt', countryCode : 'EG'},
    'Western Sahara' : { id : 'EH', countryName : 'Western Sahara', countryCode : 'EH'},
    'Eritrea' : { id : 'ER', countryName : 'Eritrea', countryCode : 'ER'},
    'Spain' : { id : 'ES', countryName : 'Spain', countryCode : 'ES'},
    'Ethiopia' : { id : 'ET', countryName : 'Ethiopia', countryCode : 'ET'},
    'Finland' : { id : 'FI', countryName : 'Finland', countryCode : 'FI'},
    'Fiji' : { id : 'FJ', countryName : 'Fiji', countryCode : 'FJ'},
    'Falkland Islands [Islas Malvinas]' : { id : 'FK', countryName : 'Falkland Islands [Islas Malvinas]', countryCode : 'FK'},
    'Micronesia' : { id : 'FM', countryName : 'Micronesia', countryCode : 'FM'},
    'Faroe Islands' : { id : 'FO', countryName : 'Faroe Islands', countryCode : 'FO'},
    'France' : { id : 'FR', countryName : 'France', countryCode : 'FR'},
    'Gabon' : { id : 'GA', countryName : 'Gabon', countryCode : 'GA'},
    'United Kingdom' : { id : 'GB', countryName : 'United Kingdom', countryCode : 'GB'},
    'Grenada' : { id : 'GD', countryName : 'Grenada', countryCode : 'GD'},
    'Georgia' : { id : 'GE', countryName : 'Georgia', countryCode : 'GE'},
    'French Guiana' : { id : 'GF', countryName : 'French Guiana', countryCode : 'GF'},
    'Guernsey' : { id : 'GG', countryName : 'Guernsey', countryCode : 'GG'},
    'Ghana' : { id : 'GH', countryName : 'Ghana', countryCode : 'GH'},
    'Gibraltar' : { id : 'GI', countryName : 'Gibraltar', countryCode : 'GI'},
    'Greenland' : { id : 'GL', countryName : 'Greenland', countryCode : 'GL'},
    'Gambia' : { id : 'GM', countryName : 'Gambia', countryCode : 'GM'},
    'Guinea' : { id : 'GN', countryName : 'Guinea', countryCode : 'GN'},
    'Guadeloupe' : { id : 'GP', countryName : 'Guadeloupe', countryCode : 'GP'},
    'Equatorial Guinea' : { id : 'GQ', countryName : 'Equatorial Guinea', countryCode : 'GQ'},
    'Greece' : { id : 'GR', countryName : 'Greece', countryCode : 'GR'},
    'South Georgia and the South Sandwich Islands' : { id : 'GS', countryName : 'South Georgia and the South Sandwich Islands', countryCode : 'GS'},
    'Guatemala' : { id : 'GT', countryName : 'Guatemala', countryCode : 'GT'},
    'Guam' : { id : 'GU', countryName : 'Guam', countryCode : 'GU'},
    'Guinea-Bissau' : { id : 'GW', countryName : 'Guinea-Bissau', countryCode : 'GW'},
    'Guyana' : { id : 'GY', countryName : 'Guyana', countryCode : 'GY'},
    'Gaza Strip' : { id : 'GZ', countryName : 'Gaza Strip', countryCode : 'GZ'},
    'Hong Kong' : { id : 'HK', countryName : 'Hong Kong', countryCode : 'HK'},
    'Heard Island and McDonald Islands' : { id : 'HM', countryName : 'Heard Island and McDonald Islands', countryCode : 'HM'},
    'Honduras' : { id : 'HN', countryName : 'Honduras', countryCode : 'HN'},
    'Croatia' : { id : 'HR', countryName : 'Croatia', countryCode : 'HR'},
    'Haiti' : { id : 'HT', countryName : 'Haiti', countryCode : 'HT'},
    'Hungary' : { id : 'HU', countryName : 'Hungary', countryCode : 'HU'},
    'Indonesia' : { id : 'ID', countryName : 'Indonesia', countryCode : 'ID'},
    'Ireland' : { id : 'IE', countryName : 'Ireland', countryCode : 'IE'},
    'Israel' : { id : 'IL', countryName : 'Israel', countryCode : 'IL'},
    'Isle of Man' : { id : 'IM', countryName : 'Isle of Man', countryCode : 'IM'},
    'India' : { id : 'IN', countryName : 'India', countryCode : 'IN'},
    'British Indian Ocean Territory' : { id : 'IO', countryName : 'British Indian Ocean Territory', countryCode : 'IO'},
    'Iraq' : { id : 'IQ', countryName : 'Iraq', countryCode : 'IQ'},
    'Iran' : { id : 'IR', countryName : 'Iran', countryCode : 'IR'},
    'Iceland' : { id : 'IS', countryName : 'Iceland', countryCode : 'IS'},
    'Italy' : { id : 'IT', countryName : 'Italy', countryCode : 'IT'},
    'Jersey' : { id : 'JE', countryName : 'Jersey', countryCode : 'JE'},
    'Jamaica' : { id : 'JM', countryName : 'Jamaica', countryCode : 'JM'},
    'Jordan' : { id : 'JO', countryName : 'Jordan', countryCode : 'JO'},
    'Japan' : { id : 'JP', countryName : 'Japan', countryCode : 'JP'},
    'Kenya' : { id : 'KE', countryName : 'Kenya', countryCode : 'KE'},
    'Kyrgyzstan' : { id : 'KG', countryName : 'Kyrgyzstan', countryCode : 'KG'},
    'Cambodia' : { id : 'KH', countryName : 'Cambodia', countryCode : 'KH'},
    'Kiribati' : { id : 'KI', countryName : 'Kiribati', countryCode : 'KI'},
    'Comoros' : { id : 'KM', countryName : 'Comoros', countryCode : 'KM'},
    'Saint Kitts and Nevis' : { id : 'KN', countryName : 'Saint Kitts and Nevis', countryCode : 'KN'},
    'North Korea' : { id : 'KP', countryName : 'North Korea', countryCode : 'KP'},
    'South Korea' : { id : 'KR', countryName : 'South Korea', countryCode : 'KR'},
    'Kuwait' : { id : 'KW', countryName : 'Kuwait', countryCode : 'KW'},
    'Cayman Islands' : { id : 'KY', countryName : 'Cayman Islands', countryCode : 'KY'},
    'Kazakhstan' : { id : 'KZ', countryName : 'Kazakhstan', countryCode : 'KZ'},
    'Laos' : { id : 'LA', countryName : 'Laos', countryCode : 'LA'},
    'Lebanon' : { id : 'LB', countryName : 'Lebanon', countryCode : 'LB'},
    'Saint Lucia' : { id : 'LC', countryName : 'Saint Lucia', countryCode : 'LC'},
    'Liechtenstein' : { id : 'LI', countryName : 'Liechtenstein', countryCode : 'LI'},
    'Sri Lanka' : { id : 'LK', countryName : 'Sri Lanka', countryCode : 'LK'},
    'Liberia' : { id : 'LR', countryName : 'Liberia', countryCode : 'LR'},
    'Lesotho' : { id : 'LS', countryName : 'Lesotho', countryCode : 'LS'},
    'Lithuania' : { id : 'LT', countryName : 'Lithuania', countryCode : 'LT'},
    'Luxembourg' : { id : 'LU', countryName : 'Luxembourg', countryCode : 'LU'},
    'Latvia' : { id : 'LV', countryName : 'Latvia', countryCode : 'LV'},
    'Libya' : { id : 'LY', countryName : 'Libya', countryCode : 'LY'},
    'Morocco' : { id : 'MA', countryName : 'Morocco', countryCode : 'MA'},
    'Monaco' : { id : 'MC', countryName : 'Monaco', countryCode : 'MC'},
    'Moldova' : { id : 'MD', countryName : 'Moldova', countryCode : 'MD'},
    'Montenegro' : { id : 'ME', countryName : 'Montenegro', countryCode : 'ME'},
    'Madagascar' : { id : 'MG', countryName : 'Madagascar', countryCode : 'MG'},
    'Marshall Islands' : { id : 'MH', countryName : 'Marshall Islands', countryCode : 'MH'},
    'Macedonia [FYROM]' : { id : 'MK', countryName : 'Macedonia [FYROM]', countryCode : 'MK'},
    'Mali' : { id : 'ML', countryName : 'Mali', countryCode : 'ML'},
    'Myanmar [Burma]' : { id : 'MM', countryName : 'Myanmar [Burma]', countryCode : 'MM'},
    'Mongolia' : { id : 'MN', countryName : 'Mongolia', countryCode : 'MN'},
    'Macau' : { id : 'MO', countryName : 'Macau', countryCode : 'MO'},
    'Northern Mariana Islands' : { id : 'MP', countryName : 'Northern Mariana Islands', countryCode : 'MP'},
    'Martinique' : { id : 'MQ', countryName : 'Martinique', countryCode : 'MQ'},
    'Mauritania' : { id : 'MR', countryName : 'Mauritania', countryCode : 'MR'},
    'Montserrat' : { id : 'MS', countryName : 'Montserrat', countryCode : 'MS'},
    'Malta' : { id : 'MT', countryName : 'Malta', countryCode : 'MT'},
    'Mauritius' : { id : 'MU', countryName : 'Mauritius', countryCode : 'MU'},
    'Maldives' : { id : 'MV', countryName : 'Maldives', countryCode : 'MV'},
    'Malawi' : { id : 'MW', countryName : 'Malawi', countryCode : 'MW'},
    'Mexico' : { id : 'MX', countryName : 'Mexico', countryCode : 'MX'},
    'Malaysia' : { id : 'MY', countryName : 'Malaysia', countryCode : 'MY'},
    'Mozambique' : { id : 'MZ', countryName : 'Mozambique', countryCode : 'MZ'},
    'Namibia' : { id : 'NA', countryName : 'Namibia', countryCode : 'NA'},
    'New Caledonia' : { id : 'NC', countryName : 'New Caledonia', countryCode : 'NC'},
    'Niger' : { id : 'NE', countryName : 'Niger', countryCode : 'NE'},
    'Norfolk Island' : { id : 'NF', countryName : 'Norfolk Island', countryCode : 'NF'},
    'Nigeria' : { id : 'NG', countryName : 'Nigeria', countryCode : 'NG'},
    'Nicaragua' : { id : 'NI', countryName : 'Nicaragua', countryCode : 'NI'},
    'Netherlands' : { id : 'NL', countryName : 'Netherlands', countryCode : 'NL'},
    'Norway' : { id : 'NO', countryName : 'Norway', countryCode : 'NO'},
    'Nepal' : { id : 'NP', countryName : 'Nepal', countryCode : 'NP'},
    'Nauru' : { id : 'NR', countryName : 'Nauru', countryCode : 'NR'},
    'Niue' : { id : 'NU', countryName : 'Niue', countryCode : 'NU'},
    'New Zealand' : { id : 'NZ', countryName : 'New Zealand', countryCode : 'NZ'},
    'Oman' : { id : 'OM', countryName : 'Oman', countryCode : 'OM'},
    'Panama' : { id : 'PA', countryName : 'Panama', countryCode : 'PA'},
    'Peru' : { id : 'PE', countryName : 'Peru', countryCode : 'PE'},
    'French Polynesia' : { id : 'PF', countryName : 'French Polynesia', countryCode : 'PF'},
    'Papua New Guinea' : { id : 'PG', countryName : 'Papua New Guinea', countryCode : 'PG'},
    'Philippines' : { id : 'PH', countryName : 'Philippines', countryCode : 'PH'},
    'Pakistan' : { id : 'PK', countryName : 'Pakistan', countryCode : 'PK'},
    'Poland' : { id : 'PL', countryName : 'Poland', countryCode : 'PL'},
    'Saint Pierre and Miquelon' : { id : 'PM', countryName : 'Saint Pierre and Miquelon', countryCode : 'PM'},
    'Pitcairn Islands' : { id : 'PN', countryName : 'Pitcairn Islands', countryCode : 'PN'},
    'Puerto Rico' : { id : 'PR', countryName : 'Puerto Rico', countryCode : 'PR'},
    'Palestinian Territories' : { id : 'PS', countryName : 'Palestinian Territories', countryCode : 'PS'},
    'Portugal' : { id : 'PT', countryName : 'Portugal', countryCode : 'PT'},
    'Palau' : { id : 'PW', countryName : 'Palau', countryCode : 'PW'},
    'Paraguay' : { id : 'PY', countryName : 'Paraguay', countryCode : 'PY'},
    'Qatar' : { id : 'QA', countryName : 'Qatar', countryCode : 'QA'},
    'Réunion' : { id : 'RE', countryName : 'Réunion', countryCode : 'RE'},
    'Romania' : { id : 'RO', countryName : 'Romania', countryCode : 'RO'},
    'Serbia' : { id : 'RS', countryName : 'Serbia', countryCode : 'RS'},
    'Russia' : { id : 'RU', countryName : 'Russia', countryCode : 'RU'},
    'Rwanda' : { id : 'RW', countryName : 'Rwanda', countryCode : 'RW'},
    'Saudi Arabia' : { id : 'SA', countryName : 'Saudi Arabia', countryCode : 'SA'},
    'Solomon Islands' : { id : 'SB', countryName : 'Solomon Islands', countryCode : 'SB'},
    'Seychelles' : { id : 'SC', countryName : 'Seychelles', countryCode : 'SC'},
    'Sudan' : { id : 'SD', countryName : 'Sudan', countryCode : 'SD'},
    'Sweden' : { id : 'SE', countryName : 'Sweden', countryCode : 'SE'},
    'Singapore' : { id : 'SG', countryName : 'Singapore', countryCode : 'SG'},
    'Saint Helena' : { id : 'SH', countryName : 'Saint Helena', countryCode : 'SH'},
    'Slovenia' : { id : 'SI', countryName : 'Slovenia', countryCode : 'SI'},
    'Svalbard and Jan Mayen' : { id : 'SJ', countryName : 'Svalbard and Jan Mayen', countryCode : 'SJ'},
    'Slovakia' : { id : 'SK', countryName : 'Slovakia', countryCode : 'SK'},
    'Sierra Leone' : { id : 'SL', countryName : 'Sierra Leone', countryCode : 'SL'},
    'San Marino' : { id : 'SM', countryName : 'San Marino', countryCode : 'SM'},
    'Senegal' : { id : 'SN', countryName : 'Senegal', countryCode : 'SN'},
    'Somalia' : { id : 'SO', countryName : 'Somalia', countryCode : 'SO'},
    'Suriname' : { id : 'SR', countryName : 'Suriname', countryCode : 'SR'},
    'São Tomé and Príncipe' : { id : 'ST', countryName : 'São Tomé and Príncipe', countryCode : 'ST'},
    'El Salvador' : { id : 'SV', countryName : 'El Salvador', countryCode : 'SV'},
    'Syria' : { id : 'SY', countryName : 'Syria', countryCode : 'SY'},
    'Swaziland' : { id : 'SZ', countryName : 'Swaziland', countryCode : 'SZ'},
    'Turks and Caicos Islands' : { id : 'TC', countryName : 'Turks and Caicos Islands', countryCode : 'TC'},
    'Chad' : { id : 'TD', countryName : 'Chad', countryCode : 'TD'},
    'French Southern Territories' : { id : 'TF', countryName : 'French Southern Territories', countryCode : 'TF'},
    'Togo' : { id : 'TG', countryName : 'Togo', countryCode : 'TG'},
    'Thailand' : { id : 'TH', countryName : 'Thailand', countryCode : 'TH'},
    'Tajikistan' : { id : 'TJ', countryName : 'Tajikistan', countryCode : 'TJ'},
    'Tokelau' : { id : 'TK', countryName : 'Tokelau', countryCode : 'TK'},
    'Timor-Leste' : { id : 'TL', countryName : 'Timor-Leste', countryCode : 'TL'},
    'Turkmenistan' : { id : 'TM', countryName : 'Turkmenistan', countryCode : 'TM'},
    'Tunisia' : { id : 'TN', countryName : 'Tunisia', countryCode : 'TN'},
    'Tonga' : { id : 'TO', countryName : 'Tonga', countryCode : 'TO'},
    'Turkey' : { id : 'TR', countryName : 'Turkey', countryCode : 'TR'},
    'Trinidad and Tobago' : { id : 'TT', countryName : 'Trinidad and Tobago', countryCode : 'TT'},
    'Tuvalu' : { id : 'TV', countryName : 'Tuvalu', countryCode : 'TV'},
    'Taiwan' : { id : 'TW', countryName : 'Taiwan', countryCode : 'TW'},
    'Tanzania' : { id : 'TZ', countryName : 'Tanzania', countryCode : 'TZ'},
    'Ukraine' : { id : 'UA', countryName : 'Ukraine', countryCode : 'UA'},
    'Uganda' : { id : 'UG', countryName : 'Uganda', countryCode : 'UG'},
    'U.S. Minor Outlying Islands' : { id : 'UM', countryName : 'U.S. Minor Outlying Islands', countryCode : 'UM'},
    'United States' : { id : 'US', countryName : 'United States', countryCode : 'US'},
    'Uruguay' : { id : 'UY', countryName : 'Uruguay', countryCode : 'UY'},
    'Uzbekistan' : { id : 'UZ', countryName : 'Uzbekistan', countryCode : 'UZ'},
    'Vatican City' : { id : 'VA', countryName : 'Vatican City', countryCode : 'VA'},
    'Saint Vincent and the Grenadines' : { id : 'VC', countryName : 'Saint Vincent and the Grenadines', countryCode : 'VC'},
    'Venezuela' : { id : 'VE', countryName : 'Venezuela', countryCode : 'VE'},
    'British Virgin Islands' : { id : 'VG', countryName : 'British Virgin Islands', countryCode : 'VG'},
    'U.S. Virgin Islands' : { id : 'VI', countryName : 'U.S. Virgin Islands', countryCode : 'VI'},
    'Vietnam' : { id : 'VN', countryName : 'Vietnam', countryCode : 'VN'},
    'Vanuatu' : { id : 'VU', countryName : 'Vanuatu', countryCode : 'VU'},
    'Wallis and Futuna' : { id : 'WF', countryName : 'Wallis and Futuna', countryCode : 'WF'},
    'Samoa' : { id : 'WS', countryName : 'Samoa', countryCode : 'WS'},
    'Kosovo' : { id : 'XK', countryName : 'Kosovo', countryCode : 'XK'},
    'Yemen' : { id : 'YE', countryName : 'Yemen', countryCode : 'YE'},
    'Mayotte' : { id : 'YT', countryName : 'Mayotte', countryCode : 'YT'},
    'South Africa' : { id : 'ZA', countryName : 'South Africa', countryCode : 'ZA'},
    'Zambia' : { id : 'ZM', countryName : 'Zambia', countryCode : 'ZM'},
    'Zimbabwe' : { id : 'ZW', countryName : 'Zimbabwe', countryCode : 'ZW'},

   

}